name: Synchronize Readme # Copied from: https://github.com/snyk/cli/blob/95f7e1021c817a44d4018c4f518061d69f6dbb5b/.github/workflows/sync-cli-help-to-user-docs.yml

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * 1-5' # Mon-Fri at 12

jobs:
  build:
    name: synchronize-readme
    runs-on: ubuntu-latest
    steps:
      - run: |
          gh auth setup-git
          git config --global user.email "noreply@snyk.io"
          git config --global user.name "$GITHUB_ACTOR"
          gh repo clone snyk/vscode-extension vscode-extension -- --depth=1 --quiet
          gh repo clone snyk/user-docs docs -- --depth=1 --quiet
          git -C ./vscode-extension checkout -b docs/automatic-gitbook-update

          cp ./docs/docs/ide-tools/visual-studio-code-extension-for-snyk-code.md ./vscode-extension/README.md
          sed -i \
              -e "s|../.gitbook/assets/|https://github.com/snyk/user-docs/raw/HEAD/docs/.gitbook/assets/|g" \
              ./vscode-extension/README.md
          sed -i \
              -E "s|^\!\\[([[:alnum:][:space:][:punct:]]*)\]\(<([[:alnum:][:punct:]\-\.\/:[:space:]\(\)]+)>\)|<img src=\"\2\" alt=\"\1\" />|g" \
              ./vscode-extension/README.md
          sed -i \
              -E 's|(\{%.*%\})||g' \
              ./vscode-extension/README.md

          if [[ $(git -C ./vscode-extension status --porcelain) ]]; then
            echo "Documentation changes detected"
            cd ./vscode-extension
            git --no-pager diff --name-only
            git add .
            git commit -m "docs: synchronizing README from snyk/user-docs"
            git push --force --set-upstream origin docs/automatic-gitbook-update
            if [[ ! $(gh pr view docs/automatic-gitbook-update 2>&1 | grep -q "no open pull requests";) ]]; then
              echo "Creating PR"
              gh pr create --title="Synchronizing README from user-docs" --body="Automatic PR controlled by GitHub Action. Please sign the commit before merging." --head docs/automatic-gitbook-update
            fi
            echo "PR exists, pushed changes to it."
          else
            echo "No documentation changes detected, exiting."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
