name: Build and Release "Preview"
on:
  push:
    branches:
      - main
jobs:
  build:
    uses: snyk/vscode-extension/.github/workflows/ci.yaml@main
    
  release-preview:
    name: Release Preview
    runs-on: ubuntu-latest
    environment: Preview
    needs: build
    steps:
      - name: Setup VSCE
        run: npm install -g vsce@latest

      - name: Fetch sources
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

        # Naming convention for the preview version means we can only release one preview per hour
      - name: Patch to preview version
        id: preview
        run: |
          VERSION=$(npm run -s patch-preview)
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
        env:
          SNYK_VSCE_AMPLITUDE_EXPERIMENT_API_KEY: ${{ secrets.SNYK_VSCE_AMPLITUDE_EXPERIMENT_API_KEY }}
          SNYK_VSCE_SENTRY_DSN_KEY: ${{ secrets.SNYK_VSCE_SENTRY_DSN_KEY }}

      - name: Package VSIX
        run: echo y | vsce package --no-git-tag-version --no-update-package-json ${{ steps.preview.outputs.version }}

      - name: Upload to S3
        env:
          AWS_S3_BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_REGION: us-east-1
        run: |
          .github/upload-to-s3.sh preview

      - name: Publish to Marketplace
        run: vsce publish -p ${{ secrets.MARKETPLACE_TOKEN }}
